### ISSUE TITLE
[bug] Lock screen weather bar is skewed

### ISSUE THREAD

**Issue by darrenmcentee** [deno750/Overdrop-Issues#22]
Hi, most of the time I get an empty black bar on the lock screen where the weather is supposed to be displayed. Please see video attached as best way to explain:
https://photos.app.goo.gl/WEiz3fraSpFP4byaA

Device: OnePlus 7 Pro, Android 10
Thanks.

**Comment by deno750** [comment]
Hello, Thanks for reporting it. Does it happens only on lock screen? Is it happening with different background colors?

**Comment by darrenmcentee** [comment]
I'm on the latest internal beta, this seems to have been fixed in v1.5.5-pro.
