### ISSUE TITLE
Issue with setup screen

### ISSUE THREAD

**Issue by 1nikolas** [deno750/Overdrop-Issues#9]
I also posted that on telegram a few days ago but no one responded. So here it is:

Hello just formated my device and I can't complete the setup screen. On automatic mode, the location icon apears and then disapears. I'm on version 1.1.10 (probably beta?). Thanks

And here is the video
https://anonfile.com/H0oa7fv3nd/2019_06_13_23_46_32_mp4

**Comment by deno750** [comment]
Can you post the video somewhere else? You can upload it here in GitHub

**Comment by 1nikolas** [comment]
@deno750 sorry I forgot to close the issue. It was fixed with the alpha update on tg

**Comment by deno750** [comment]
Thanks. If you have any other problem, just open another issue. Regards
